version: '3.7'

services:
  ktor-blog:
    build: .
    container_name: ktor-blog
    networks:
      - app-network
    ports:
      - "80:80"
    env_file:
      - ./src/.env

  ktor-nginx:
    image: nginx:stable-alpine
    container_name: ktor-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ktor-blog
    networks:
      - app-network

networks:
  app-network:
    driver: bridge